graphql-java/graphql-java-page

content/contact/_index.md
Link with slash at end of URL redirect to home page of Spectrum chat ("Explore"). Only link without slash is correct URL to Spectrum room (in this case "GraphQL Java").
=> Fix link to Spectrum chat

content/documentation/master/execution.md
Links to graphql spec have been updated with the new location, using the newest (_draft_) version
=> Fix links to graphql spec

content/documentation/v13/data-fetching.md
Changes, _the context is object is_ to _the context object is_.
=> Fix Typo in Docs

content/documentation/master/getting-started.md, content/documentation/v10/getting-started.md, content/documentation/v11/getting-started.md, content/documentation/v12/getting-started.md, content/documentation/v13/getting-started.md, content/documentation/v14/getting-started.md, content/documentation/v9/getting-started.md
fixes #32 
fixes graphql-java/graphql-java#1873
=> 32: Use https in dependency definitions

content/documentation/master/sdl-directives.md, content/documentation/v10/batching.md, content/documentation/v10/sdl-directives.md, content/documentation/v11/batching.md, content/documentation/v11/sdl-directives.md, content/documentation/v12/batching.md, content/documentation/v12/sdl-directives.md, content/documentation/v13/batching.md, content/documentation/v13/sdl-directives.md, content/documentation/v14/batching.md, content/documentation/v14/sdl-directives.md, content/documentation/v15/batching.md, content/documentation/v15/sdl-directives.md, content/documentation/v9/batching.md, content/documentation/v9/sdl-directives.md
This PR fixes some minor typos.
=> Fix minor typos in MarkDown

content/documentation/v16/getting-started.md
Not quite sure which branch should it point to, would be grateful if a maintainer could help me out with that.
=> Fix a typo in the v16 getting started Maven code block

documentation/execution.md, versioned_docs/version-v18/execution.md, versioned_docs/version-v19/execution.md
Just a tiny PR to fix a typo I noticed while reading the documentation.
=> Typo: hit ration should be hit ratio

documentation/batching.md, versioned_docs/version-v18/batching.md, versioned_docs/version-v19/batching.md
Just a couple of more typo fixes.
=> Fix small typos on Batching page

documentation/scalars.md, versioned_docs/version-v18/scalars.md, versioned_docs/version-v19/scalars.md
Update with coercing nullability, tidy up the wording
Note, I have not changed the nullability wording in v18, as the changes were merged in after v18.
This Scalars page ought to also discuss `valueToLiteral` coercing, I will add this in another PR.
=> Update scalars coercing nullability

documentation/batching.md, versioned_docs/version-v19/batching.md
Two language typos fixed (minor)
=> Fixed typos in 'batching' documentation page

blog/2022-09-20-spring-for-graphql-naming.md, blog/authors.yml
Draft blog clarifying confusion regarding name of current Spring integration. "Spring for GraphQL" is the official Spring integration.
=> Add clarification blog on Spring integration recommendation

documentation/instrumentation.md, versioned_docs/version-v20/instrumentation.md
With v20, state is now passed into instrumentation hooks as a parameter directly.
=> Add Instrumentation hooks with state parameters

documentation/scalars.md, versioned_docs/version-v20/scalars.md, versioned_docs/version-v21/scalars.md
Fixes up our documentation to use the current versions of the scalar coercion methods. This update is for master, v21, and v20 docs.
We save our examples in GraphQL Java - see the corresponding PR where I check in the updated example https://github.com/graphql-java/graphql-java/pull/3413
=> Update deprecated methods in scalar coercion documentation

documentation/execution.md, versioned_docs/version-v20/execution.md, versioned_docs/version-v21/execution.md
The old `accept` method was replaced years ago!
Update with current method signature and fix code block
=> Fix method signature for DataFetcherExceptionHandler

documentation/execution.md, versioned_docs/version-v22/execution.md
Version 22.0 of `graphql-java` removed a deprecated method from the `PreparsedDocumentProvider` interface.
This means that the example code for setting up a Query Cache, which used the deprecated method, no longer compiles.
This PR updates the documentation so that it will compile.
Note that I'm not sure whether there's a better solution than using `CompletableFuture.completedFuture()`, so open to suggestions.
=> Fix Query Caching section so that example code compiles

blog/2023-03-21-release-policy.md, documentation/sdl-directives.md
A while back we changed from approximately 2 releases per year to 4, which made releases rather thin. We've re-adjusted this to be 3 releases per year.
Otherwise our timelines for security and bug fixes are unchanged.
=> Update release policy

blog/2024-12-07-cve-numbering-authority.md, src/pages/security.md
Announcing GraphQL Java is now a CVE Numbering Authority
=> Add CNA blog and security information

documentation/concerns.md, documentation/data-fetching.md, documentation/sdl-directives.md, versioned_docs/version-v22/concerns.md, versioned_docs/version-v22/data-fetching.md, versioned_docs/version-v22/sdl-directives.md
Removing references to `getContext`, because it was deprecated in favour of `getGraphQLContext`
=> Update documentation to remove deprecated methods

documentation/batching.md
This is a new feature coming in v25.0, and is available via the preview version v25.0.beta-2
This is written taking into account feedback regarding the confusion of the batch window configuration
=> Add documentation for Chained DataLoaders

documentation/profiler.md
Learned today that the engine timing is set right after all instrumentations, so if you're logging from within an instrumentation, you won't get the engine timing info
All other information such as DataLoader invocations remains valid. It's only the timer that is not recorded before the instrumentation runs
=> Add a note on instrumentation logging not having access to engine timing
