content/documentation/master/schema.md
content/documentation/v11/schema.md

Added notes on how to make a programmatically-generated schema executable

Updated Programmatic Schemas section

---

content/tutorials/getting-started-with-spring-boot.md

Making various sentences flow better in the getting started documentation.

Amend getting started documentation

---

content/documentation/v13/execution.md

doc(v13): Update Query Caching example

---

content/documentation/master/execution.md
content/documentation/v10/execution.md
content/documentation/v11/execution.md
content/documentation/v12/execution.md
content/documentation/v13/execution.md
content/documentation/v14/execution.md
content/documentation/v15/execution.md
content/documentation/v9/execution.md

Just a minor wording issue I noticed while reading the docs. Thanks!

fix consider -> considered typo

---

content/documentation/v12/execution.md
content/documentation/v13/execution.md
content/documentation/v14/execution.md

19: Fix DataFetcherExceptionHandler example

---

config.toml
content/documentation/master/batching.md
content/documentation/master/getting-started.md
content/documentation/v16/getting-started.md
content/documentation/v16/schema.md

Updating latest version to 16.1 as well as correcting a few typos along the way

Minor documentation fixes (version 16.1 and typos)

---

content/documentation/v16/instrumentation.md

Adds documentation for
MaxQueryComplexityInstrumentation
and
MaxQueryDepthInstrumentation

Add query analysis instrumentation docs

---

documentation/getting-started.md
documentation/scalars.md
versioned_docs/version-v17/getting-started.md
versioned_docs/version-v17/scalars.md

Fixes graphql-java/graphql-java#2592

Fix GraphQLScalar documentation

---

documentation/getting-started.md
versioned_docs/version-v16/getting-started.md
versioned_docs/version-v17/getting-started.md
versioned_docs/version-v18/getting-started.md

Remove references to Bintray with Maven Central (for latest snapshot builds)

docs: remove bintray references

---

documentation/getting-started.mdx
docusaurus.config.js
readme.md
versioned_docs/version-v18/getting-started.mdx

This PR adds Kotlin tabs, thanks to @[jord1e](https://github.com/jord1e)

Add tabs, updated from jord1e's PR

---

src/pages/tutorials/getting-started-with-spring-boot.md

While trying to understand the tutorial page, I got confused whether totalPages is a typo, but on further investigation I observe its intended to explain default datafetcher and how to handle key mismatch scenario.
I have added a code snippet in order to reflect this intention in a more friendly way.

Added java changes under Default DataFetchers

---

documentation/batching.md
documentation/contributions.md
documentation/getting-started.mdx
documentation/schema.md
versioned_docs/version-v18/batching.md
versioned_docs/version-v18/contributions.md
versioned_docs/version-v18/getting-started.mdx
versioned_docs/version-v18/schema.md
versioned_docs/version-v19/batching.md
versioned_docs/version-v19/contributions.md
versioned_docs/version-v19/getting-started.mdx
versioned_docs/version-v19/schema.md

Fixing up header anchor links and typos

Headers anchor link fix

---

versioned_docs/version-v19/data-fetching.md

Just fixing a mismatched quote in the schema example

Update data-fetching.md to fix mismatched quote

---

documentation/execution.md
versioned_docs/version-v18/execution.md
versioned_docs/version-v19/execution.md

Some minor corrections to make the sample code syntactically correct Java.

Fix sample code in Query Caching section

---

documentation/getting-started.mdx
versioned_docs/version-v19/getting-started.mdx

Wait for release before merging - this will autodeploy

Update to 19.2

---

documentation/data-mapping.md
versioned_docs/version-v20/data-mapping.md

I was asked on how input types are represented at runtime so I thought I would add some doco for that

Added doco on how input types are represented

---

src/pages/tutorials/getting-started-with-spring-boot.md

To be consistent with Spring for GraphQL documentation https://docs.spring.io/spring-graphql/docs/current/reference/html/#overview

Update Spring samples link

---

documentation/getting-started.mdx
versioned_docs/version-v19/getting-started.mdx
versioned_docs/version-v20/getting-started.mdx

Update doco with new v20 and v19 versions

V20.1 release

---

versioned_docs/version-v20/getting-started.mdx

Add v20.5 to docs

---

versioned_docs/version-v20/getting-started.mdx

To be merged after we release the latest v20 shortly

New version with missing Guava patch

---

docusaurus.config.js

Thanks to https://github.com/graphql-java/graphql-java/issues/3382 for reporting

Make latest version v21

---

src/pages/tutorials/getting-started-with-spring-boot.md

I know not everyone uses Spring, so let's add a guide that is pure GraphQL Java https://github.com/graphql-java/graphql-java/discussions/3500#discussioncomment-8680589

Add community tutorial

---

docusaurus.config.js
src/pages/security.md

Adds security policy and information

Add security information

---

src/pages/security.md

Add security policy tweaks

---

documentation/sdl-directives.md
versioned_docs/version-v22/sdl-directives.md

Fixes issue raised in graphql-java repo. Example was out of date after changes in v22 https://github.com/graphql-java/graphql-java/issues/3576
graphql-java PR where deprecated methods were removed: https://github.com/graphql-java/graphql-java/pull/3514/files

Fix SDL documentation page

---

documentation/getting-started.mdx
versioned_docs/version-v22/getting-started.mdx

Update documentation to 22.2

---

documentation/getting-started.mdx
versioned_docs/version-v22/getting-started.mdx

For the 22.3 release coming out in a bit

Update latest to 22.3

---

documentation/limits.md
versioned_docs/version-v21/limits.md
versioned_docs/version-v22/limits.md

Creating a documentation page from this discussion response https://github.com/graphql-java/graphql-java/discussions/3738

Add parser limit documentation

---

documentation/batching.md
versioned_docs/version-v21/batching.md
versioned_docs/version-v22/batching.md

Add repo link earlier so it's earlier this is contained in a separate library

Add link to dataloader repo

---

documentation/getting-started.mdx
versioned_docs/version-v24/getting-started.mdx

Update to 24.2

---

documentation/profiler.md

For the Profiler that will be included in v25.0, or currently available in the latest beta release
Note I am only including this in the master documentation for now.

Add Profiler documentation
